spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: r1
          uri: http://localhost:8081
          predicates:
            - Path= /api/events/**
        - id: r2
          uri: http://localhost:8082
          predicates:
            - Path= /auth/** , /login
